# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd503434e24a4d46d510c0026086b144b8e586fc6eeac387c68eac40ddfdee57697782e4f5ef727b6ba6b43c8a4fa93c4560b401425e3f7b07af3dc887f1f824

test:
  secret_key_base: 9581a90d8e8722a9251dde30430beb2ec05bdd545ead06fd97f10e50c6b411d793f3f41a572435b33c88607e1b366bfc3d75b633dc51c80dd25bed1bbf768f65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
